# Generated by Django 4.0 on 2022-01-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandtable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RGBW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.IntegerField(default=0)),
                ('g', models.IntegerField(default=0)),
                ('b', models.IntegerField(default=0)),
                ('w', models.IntegerField(default=0)),
                ('led_track', models.CharField(default='None', max_length=100)),
                ('changed', models.BooleanField(default=False)),
            ],
        ),
    ]
