# Generated by Django 4.0 on 2022-02-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandtable', '0002_rgbw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_speed', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='rgbw',
            name='led_speed',
            field=models.IntegerField(default=100),
        ),
    ]
