# Generated by Django 4.0 on 2022-10-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandtable', '0003_settings_rgbw_led_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='rgbw',
            name='led_intensity',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='rgbw',
            name='led_saturation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rgbw',
            name='led_speed',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='settings',
            name='motor_speed',
            field=models.IntegerField(default=1),
        ),
    ]
