# Generated by Django 4.1.3 on 2022-12-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandtable', '0005_settings_r_settings_theta'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='calibrate',
            field=models.IntegerField(default=0),
        ),
    ]
